server:
  port: 8888
spring:
  application:
    name: demoapp
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test
  threads:
    virtual:
      enabled: true


management:
  tracing:
    sampling:
      probability: 1.0
    enabled: true
    zipkin:
      endpoint: http://localhost:9411/api/v2/spans

  prometheus:
    endpoints:
      web:
        exposure:
          include: health,metrics,observability,prometheus
    metrics:
      export:
        enabled: true
      mongo:
        command:
          enabled: false

solace:
  java:
    host: localhost:55555
    msgVpn: default
    clientUsername: admin
    clientPassword: admin
    queueName: test

logging:
  pattern:
    level: "%5p [${spring.application.name:}, traceId=%X{traceId}, spanId=%X{spanId}]"



