server:
  port: 8888
spring:
  application:
    name: demoapp
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test
  threads:
    virtual:
      enabled: true
  cloud:
    function:
      definition: sink
    stream:
      bindings:
        sink-in-0:
          destination: TEMPS.Q
          #The presence of "group" tells the binder to follow the "consumer group" pattern
          group: SINK
          binder: solace-broker
          consumer:
            #Concurrency can be used with a consumer group (non-exclusive queue) to process events in multiple threads
            concurrency: 5
      binders:
        solace-broker:
          type: solace
          environment:
            solace:
              java:
                host: tcp://localhost:55555
                msgVpn: default
                clientUsername: admin
                clientPassword: admin
                connectRetries: -1
                reconnectRetries: -1

management:
  tracing:
    sampling:
      probability: 1.0
    enabled: true
    zipkin:
      endpoint: http://localhost:9411/api/v2/spans

  prometheus:
    endpoints:
      web:
        exposure:
          include: health,metrics,observability,prometheus
    metrics:
      export:
        enabled: true
