spring:
  application:
    name: app

  data:
    mongodb:
      host: localhost
      port: 27017
      database: test

  threads:
    virtual:
      enabled: true

tracing:
  url: http://localhost:4318/v1/traces

management:
  tracing:
    sampling:
      probability: 1.0




